app:
  port: 8080

database:
  host: db
  port: 3306
  user: root
  password: greygoose
  name: db_name

auth:
  jwt_access_secret: super-secret-access-key-change-me
  jwt_refresh_secret: super-secret-refresh-key-change-me
  access_ttl_minutes: 15
  refresh_ttl_hours: 168
